### ISSUE TITLE
template files for LocalAI?

### ISSUE THREAD

**Issue by Anto79-ops** [MeetKai/functionary#102]
Hello!

I'm trying to run the GGUF version of the medium model, functionary-medium-v2.2-GGUF using LocalAI. Unfortaintly, I do not know how to make the template files to use this with LocalAI. LocalAI typically require 2 (or more files), typcally `chat-block.tmpl` and `chat.tmpl` that work with the model.yaml and the gguf file for example [here](https://io.midori-ai.xyz/howtos/easy-model/).

it does not seem to work with your typical model settings like:

the "chat-block.tmpl",  (this is a template that model “Chat” trained models use, but changed for LocalAI)

```
<|im_start|>{{if eq .RoleName "assistant"}}assistant{{else if eq .RoleName "system"}}system{{else if eq .RoleName "user"}}user{{end}}
{{if .Content}}{{.Content}}{{end}}
<|im_end|>
```

and 'chat.tmpl`, 

```
{{.Input}}
<|im_start|>assistant
```

and also, not sure of the "stop words" to be used, like

```
stopwords:
- "user|"
- "assistant|"
- "system|"
- "<|im_end|>"
- "<|im_start|>"
template:
  chat: chat
  chat_message: chat-block
```

any help to get this running on LocalAI would be great!
